default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_development" %>
  cable:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_development_cable" %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_development_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_development_queue" %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_test" %>
  cable:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_test_cable" %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_test_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_test_queue" %>
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_cable" %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= "#{ENV["DATABASE_URL"]}_queue" %>
    migrations_paths: db/queue_migrate
