default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 16).to_i %>
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
